# Generated by Django 4.1.2 on 2022-10-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_area_alter_project_options_project_id_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='about',
            field=models.TextField(max_length=400),
        ),
    ]
