# Generated by Django 4.1.2 on 2022-10-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_about'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='area',
            table='area',
        ),
    ]
